# -*- coding: utf-8 -*-
"""session3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GI-t5znYQmCCH0C4Fr71iTg5QU5wytW
"""

import csv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
import cv2
import rawpy



data = pd.read_csv("close_objects_seq.csv",parse_dates=True, index_col=0) 
# Preview the first 10 lines of the loaded data 
data.head(5)

frame_data = data
centerX = data.center_x.array
centerY = data.center_y.array
xSize = data.x_size.array
ySize = data.y_size.array
xtl = data.xtl_area.array
xbr = data.xbr_area.array
ytl = data.ytl_area.array
ybr = data.ybr_area.array

print(centerX)
#for x in centerX:
 # print(x)

pip install rawpy

pip install rawpy

def read_image(path_of_frame):
  end_file = path_of_frame[-3:]
  if end_file == 'dng':
    with rawpy.imread(path_of_frame) as raw:
      return raw.postprocess()
  elif end_file == 'png':
    return cv2.cvtColor(cv2.imread(path_of_frame), cv2.COLOR_BGR2RGB)  
  else:
    raise Exception("Un supported file type")
image_read = read_image(r'new.dng')

image_read
plt.imshow(image_read)

print(f'{xtl[0]}, {ybr[0]}')



#print(f'{xtl[1]},{xbr[1]},{ytl[1]},{ybr[1]}')
lxpos = int(xtl[0])
rxpos = int(xbr[0])
lypos = int(ytl[0])
rypos = int(ybr[0])
print(lxpos)

crop_img = image_read[int(xtl[0]):int(xbr[0])+300,int(ytl[0]):int(ybr[0])+300,: ]
#cv2.rectangle(crop_img,(lypos-50,rypos+50),(lxpos-50,rxpos+50),(255,0,0),1,)
#crop_img = image_read[int(xtl[1],int(ybr[1]),:]
print(type(crop_img))
print(crop_img.shape)
plt.imshow(crop_img)

















